# Extend vert.x image
FROM vertx/vertx4

# Verticles
ENV FORECAST_VERTICLE_NAME com.expert.mark.controller.ForecastVerticle
ENV DELPHI_QUIZ_VERTICLE_NAME com.expert.mark.controller.DelphiQuizVerticle
ENV FORECAST_DELPHI_QUIZ_VERTICLE_FILE ./forecast/target/forecast-1.0-SNAPSHOT.jar

ENV RECOMMENDATION_VERTICLE_NAME com.expert.mark.controller.RecommendationController
ENV RECOMMENDATION_VERTICLE_FILE recommendation/target/recommendation-1.0-SNAPSHOT.jar

ENV SECURITY_VERTICLE_NAME com.expert.mark.verticle.SecurityVerticle
ENV SECURITY_VERTICLE_FILE security/target/security-1.0-SNAPSHOT.jar

ENV USER_VERTICLE_NAME com.expert.mark.controller.UserController
ENV USER_VERTICLE_FILE user/target/user-1.0-SNAPSHOT.jar

ENV CURRENCY_VERTICLE_NAME com.expert.mark.verticle.CurrencyVerticle
ENV CURRENCY_VERTICLE_FILE currency/target/currency-1.0-SNAPSHOT.jar

ENV SPY_VERTICLE_NAME com.expert.mark.verticle.SpyVerticle
ENV SPY_VERTICLE_FILE spy/target/spy-1.0-SNAPSHOT.jar

# Util modules
ENV MODEL_FILE  model/target/model-1.0-SNAPSHOT.jar
ENV UTIL_FILE  util/target/util-1.0-SNAPSHOT.jar
ENV EXPERT_STATISTIC_FILE expertStatistic/target/expertStatistic-1.0-SNAPSHOT.jar

# Set the location of the jars
ENV FORECAST_DELPHI_QUIZ_VERTICLE_HOME /usr/forecastDelphiQuizVerticle
ENV CURRENCY_VERTICLE_HOME /usr/currencyVerticle
ENV RECOMMENDATION_VERTICLE_HOME /usr/recommendationVerticle
ENV SPY_VERTICLE_HOME /usr/spyVerticle
ENV USER_VERTICLE_HOME /usr/userVerticle
ENV SECURITY_VERTICLE_HOME /usr/securityVerticle
ENV MODEL_HOME /usr/model
ENV UTIL_HOME /usr/util
ENV EXPERT_STATISTIC_HOME /usr/expertStatistic

ENV JARS_HOME /usr/jarsHome

EXPOSE 8081
EXPOSE 8082
EXPOSE 8083
EXPOSE 8084
EXPOSE 8085
EXPOSE 8088

# Copy your verticles to the container
COPY $FORECAST_DELPHI_QUIZ_VERTICLE_FILE $FORECAST_DELPHI_QUIZ_VERTICLE_HOME/
COPY $CURRENCY_VERTICLE_FILE $CURRENCY_VERTICLE_HOME/
COPY $EXPERT_STATISTIC_FILE $EXPERT_STATISTIC_HOME/
COPY $MODEL_FILE $MODEL_HOME/
COPY $RECOMMENDATION_VERTICLE_FILE $RECOMMENDATION_VERTICLE_HOME/
COPY $SECURITY_VERTICLE_FILE $SECURITY_VERTICLE_HOME/
COPY $SPY_VERTICLE_FILE $SPY_VERTICLE_HOME/
COPY $USER_VERTICLE_FILE $USER_VERTICLE_HOME/
COPY $UTIL_FILE $UTIL_HOME/

ENV FORECAST_DELPHI_QUIZ_VERTICLE_CLASSPATH "$FORECAST_DELPHI_QUIZ_VERTICLE_HOME/forecast-1.0-SNAPSHOT.jar:$MODEL_HOME/model-1.0-SNAPSHOT.jar:$USER_VERTICLE_HOME/user-1.0-SNAPSHOT.jar:$EXPERT_STATISTIC_HOME/expertStatistic-1.0-SNAPSHOT.jar:$UTIL_HOME/:util-1.0-SNAPSHOT.jar"
ENV SPY_CLASSPATH "$SPY_VERTICLE_HOME/spy-1.0-SNAPSHOT.jar:$UTIL_HOME/util-1.0-SNAPSHOT.jar"
ENV RECOMMENDATION_VERTICLE_CLASSPATH "$RECOMMENDATION_VERTICLE_HOME/recommendation-1.0-SNAPSHOT.jar:$FORECAST_DELPHI_QUIZ_VERTICLE_HOME/forecast-1.0-SNAPSHOT.jar:$USER_VERTICLE_HOME/user-1.0-SNAPSHOT.jar:$UTIL_HOME/util-1.0-SNAPSHOT.jar"
ENV SECURITY_VERTICLE_CLASSPATH "$SECURITY_VERTICLE_HOME/security-1.0-SNAPSHOT.jar:$USER_VERTICLE_HOME/user-1.0-SNAPSHOT.jar"
ENV USER_VERTICLE_CLASSPATH "$USER_VERTICLE_HOME/user-1.0-SNAPSHOT.jar:$EXPERT_STATISTIC_HOME/expertStatistic-1.0-SNAPSHOT.jar:$MODEL_HOME/model-1.0-SNAPSHOT.jar:$UTIL_HOME/util-1.0-SNAPSHOT.jar"

# Launch the verticles
ENTRYPOINT ["sh", "-c"]
CMD ["exec vertx run $CURRENCY_VERTICLE_NAME -cp $CURRENCY_VERTICLE_HOME/*.jar -cluster"]
CMD ["exec vertx run $FORECAST_VERTICLE_NAME -cp $FORECAST_DELPHI_QUIZ_VERTICLE_CLASSPATH -cluster"]
CMD ["exec vertx run $SPY_VERTICLE_NAME -cp $SPY_CLASSPATH -cluster"]
CMD ["exec vertx run $RECOMMENDATION_VERTICLE_NAME -cp $RECOMMENDATION_VERTICLE_CLASSPATH -cluster"]
CMD ["exec vertx run $SECURITY_VERTICLE_NAME -cp $SECURITY_VERTICLE_CLASSPATH -cluster"]
CMD ["exec vertx run $USER_VERTICLE_NAME -cp $USER_VERTICLE_CLASSPATH -cluster"]
